<a href="https://colab.research.google.com/github/ilham-fikri/Tugas-Data-Mining-3/blob/main/Tugas_Data_Mining_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('Barubuat.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Biologi' 24.0 10.0]
 ['Fisika' 25.0 12.0]
 ['Olahraga' 23.0 10.0]
 ['Agama' 40.0 16.0]
 ['Olahraga' 20.0 8.0]
 ['Agama' 35.0 11.0]
 ['Biologi' 38.0 nan]
 ['Matematika' nan 18.0]
 ['Fisika' 12.0 19.0]
 ['Agama' 29.0 20.0]
 ['Matematika' 31.0 9.0]
 ['Fisika' nan 8.0]
 ['Biologi' 22.0 nan]]


In [ ]:
print(y)

['No' 'Yes' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['Biologi' 24.0 10.0]
 ['Fisika' 25.0 12.0]
 ['Olahraga' 23.0 10.0]
 ['Agama' 40.0 16.0]
 ['Olahraga' 20.0 8.0]
 ['Agama' 35.0 11.0]
 ['Biologi' 38.0 12.818181818181818]
 ['Matematika' 27.181818181818183 18.0]
 ['Fisika' 12.0 19.0]
 ['Agama' 29.0 20.0]
 ['Matematika' 31.0 9.0]
 ['Fisika' 27.181818181818183 8.0]
 ['Biologi' 22.0 12.818181818181818]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 1.0 0.0 0.0 0.0 24.0 10.0]
 [0.0 0.0 1.0 0.0 0.0 25.0 12.0]
 [0.0 0.0 0.0 0.0 1.0 23.0 10.0]
 [1.0 0.0 0.0 0.0 0.0 40.0 16.0]
 [0.0 0.0 0.0 0.0 1.0 20.0 8.0]
 [1.0 0.0 0.0 0.0 0.0 35.0 11.0]
 [0.0 1.0 0.0 0.0 0.0 38.0 12.818181818181818]
 [0.0 0.0 0.0 1.0 0.0 27.181818181818183 18.0]
 [0.0 0.0 1.0 0.0 0.0 12.0 19.0]
 [1.0 0.0 0.0 0.0 0.0 29.0 20.0]
 [0.0 0.0 0.0 1.0 0.0 31.0 9.0]
 [0.0 0.0 1.0 0.0 0.0 27.181818181818183 8.0]
 [0.0 1.0 0.0 0.0 0.0 22.0 12.818181818181818]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 1 1 0 0 1 1 0 0 1 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [ ]:
print(x_train)

[[0.0 0.0 0.0 1.0 0.0 31.0 9.0]
 [0.0 0.0 1.0 0.0 0.0 25.0 12.0]
 [0.0 1.0 0.0 0.0 0.0 38.0 12.818181818181818]
 [0.0 1.0 0.0 0.0 0.0 24.0 10.0]
 [0.0 0.0 0.0 1.0 0.0 27.181818181818183 18.0]
 [0.0 1.0 0.0 0.0 0.0 22.0 12.818181818181818]
 [1.0 0.0 0.0 0.0 0.0 29.0 20.0]
 [0.0 0.0 1.0 0.0 0.0 12.0 19.0]
 [0.0 0.0 1.0 0.0 0.0 27.181818181818183 8.0]
 [1.0 0.0 0.0 0.0 0.0 35.0 11.0]]


In [ ]:
print(x_test)

[[0.0 0.0 0.0 0.0 1.0 23.0 10.0]
 [1.0 0.0 0.0 0.0 0.0 40.0 16.0]
 [0.0 0.0 0.0 0.0 1.0 20.0 8.0]]


In [ ]:
print(y_train)

[1 1 1 0 1 1 0 0 0 0]


In [ ]:
print(y_test)

[1 1 0]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 4:] = sc.fit_transform(x_train[:, 4:])
x_test[:, 4:] = sc.transform(x_test[:, 4:])

In [ ]:
print(x_train)

[[0.0 0.0 0.0 1.0 0.0 0.5793571050062895 -1.0516408817475782]
 [0.0 0.0 1.0 0.0 0.0 -0.2976513567004795 -0.3116803466160197]
 [0.0 1.0 0.0 0.0 0.0 1.6025336436641864 -0.1098729279437764]
 [0.0 1.0 0.0 0.0 0.0 -0.44381943365160764 -0.8049873700370587]
 [0.0 0.0 0.0 1.0 0.0 0.021260811192891246 1.1682407236470973]
 [0.0 1.0 0.0 0.0 0.0 -0.736155587553864 -0.1098729279437764]
 [1.0 0.0 0.0 0.0 0.0 0.2870209511040331 1.6615477470681363]
 [0.0 0.0 1.0 0.0 0.0 -2.1978363570651456 1.4148942353576168]
 [0.0 0.0 1.0 0.0 0.0 0.021260811192891246 -1.2982943934580977]
 [1.0 0.0 0.0 0.0 0.0 1.164029412810802 -0.5583338583265391]]


In [ ]:
print(x_test)

[[0.0 0.0 0.0 0.0 1.0 -0.5899875106027358 -0.8049873700370587]
 [1.0 0.0 0.0 0.0 0.0 1.8948697975664428 0.6749337002260584]
 [0.0 0.0 0.0 0.0 1.0 -1.0284917414561203 -1.2982943934580977]]
